baseurl = "https://freezz.cc"
title = "自游鱼"
languageCode = "en-us" # 设置网站使用的语言代码，这里是美国英语
defaultContentLanguage = "zh-cn" # 设置网站默认语言为中文(若去掉这一行则默认英文)
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # DEPRECATED! Use .Services.Disqus.Shortname
googleAnalytics = "" # DEPRECATED! Use .Services.googleAnalytics.ID

[Params.style.vars]
  highlightColor = "#2956a3" # Override highlight color

[Params]
  description = "自游鱼的博客 电脑技术 互联网技术 AI技术 网络" # 网站的描述
  copyright = "John Doe" # 版权信息
  opengraph = true # 启用OpenGraph，有助于社交媒体上的分享
  schema = true # 启用Schema.org标记，有助于SEO
  twitter_cards = true # 启用Twitter卡片，优化Twitter分享
  readmore = false # 是否在列表页显示“阅读更多”按钮
  # authorbox = true # 是否在页面底部显示作者信息框
  toc = true # 是否启用文章的目录（Table of Contents）
  pager = true # 是否在页面底部显示翻页导航（前一篇/后一篇链接）
  post_meta = ["author", "date", "categories", "translations"] # 文章元信息显示的顺序
  # mainSections = ["post", "blog", "news"] # 指定在首页和“最近文章”小部件中显示哪些部分的页面
  dateformat = "2006-01-02" # 日期的显示格式

# 用于设置网站Logo的参数
[Params.logo]
# image = "img/logo.png"
subtitle = "从原点再出发,不是简单的重复" # Logo的副标题

# 侧边栏的配置
[Params.sidebar]
  home = "right" # 首页侧边栏的布局
  list = "right"  # 列表页侧边栏的布局
  single = true # 文章页是否显示侧边栏
  widgets = ["search","featured", "recent", "categories", "taglist", "social", "languages"] # 启用的小部件及其顺序, # 其中featured就是“精选文章”小部件

[Params.thumbnail]
  visibility = ["list", "post"] # 缩略图的显示设置

[Params.widgets]
# 小部件的具体配置
recent_num = 5 # “最近文章”小部件显示的文章数量
featured_num = 10 # “精选文章”小部件显示的文章数量

[outputs]
  home = ["HTML", "RSS", "JSON"]

